-- Canonical schema is embedded in tls_multi_registry.py so the CLI can
-- initialize a fresh database without a migration dependency.
-- This file is a human-readable marker for deployment reviews.
-- Current executable schema version: 3 (task groups and delivery leases).
-- See tls_multi_registry.py:SCHEMA and Registry._migrate_schema().
